import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { Sidebar } from "@/components/Siderbar/Sidebar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "MyKomar",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <Sidebar
                        loggedUser={{
                            fullName: "Jacob K",
                            code: "WWW7/22",
                        }}
                    />
                    {children}
                </Providers>
            </body>
        </html>
    );
}
