import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { SLayout } from "./styles";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "MyKomar",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <SLayout>{children}</SLayout>
                </Providers>
            </body>
        </html>
    );
}
