import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { Sidebar } from "@/components/Siderbar/Sidebar";
import { SLayout, SMain, SMainLogin } from "./styles";
import { cache } from "react";
import { getStudent } from "@/lib/student";

// import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//     title: "MyKomar",
//     description: "Generated by create next app",
// };

export default async function RootLayout({ children }) {
    const user = await getStudent();

    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <SLayout>
                        <Sidebar user={user} />
                        <SMain>{children}</SMain>
                        {/* {login ? (
                            <>
                                <Sidebar
                                    loggedUser={{
                                        fullName: "Jacob K",
                                        code: "F201139",
                                    }}
                                />
                                <SMain>{children}</SMain>
                            </>
                        ) : (
                            <>
                                <SMainLogin>{children}</SMainLogin>
                            </>
                        )} */}
                    </SLayout>
                </Providers>
            </body>
        </html>
    );
}
